### ISSUE TITLE
LoginError happens occasionally

### ISSUE THREAD

**Issue by llamafilm** [tchellomello/python-amcrest#222]
I'm using this library via Home Assistant and I occasionally see Login Errors in the log.  It always resolves itself within a few seconds, I'm just trying to figure out what causes it.  I first posted  in https://github.com/home-assistant/core/issues/85859.  Here's a log snippet showing that it fails with error 401 and then immediately tries again and succeeds.  Any ideas what causes this?

```
22:26:28.658 DEBUG [amcrest.http] <AMC06058C8E8315D89:AMC06058C8E8315D89> Trying async Basic Authentication
22:26:28.658 DEBUG [amcrest.http] <AMC06058C8E8315D89:AMC06058C8E8315D89> Async HTTP query 2825: http://192.168.20.10:80/cgi-bin/magicBox.cgi?action=getMachineName
22:26:28.685 DEBUG [amcrest.http] <AMC06058C8E8315D89:AMC06058C8E8315D89> Running query 2825 attempt 1
22:26:29.736 DEBUG [amcrest.http] <AMC06058C8E8315D89:AMC06058C8E8315D89> Query 2825: Unauthorized (401)

22:26:29.739 DEBUG [amcrest.http] <AMC06058C8E8315D89:AMC06058C8E8315D89> Trying async Digest Authentication
22:26:29.740 DEBUG [amcrest.http] <AMC06058C8E8315D89:AMC06058C8E8315D89> Async HTTP query 2826: http://192.168.20.10:80/cgi-bin/magicBox.cgi?action=getMachineName
22:26:29.765 DEBUG [amcrest.http] <AMC06058C8E8315D89:AMC06058C8E8315D89> Running query 2826 attempt 1
22:26:31.103 DEBUG [amcrest.http] <AMC06058C8E8315D89:AMC06058C8E8315D89> Query 2826 worked. Exit code: <200>
```

Here in the code it looks like this situation is handled by the duplicate `DigestAuth` call, so I'm curious if this is a known issue?
https://github.com/tchellomello/python-amcrest/blob/b9883a246d92580d49d2c6c6435af1dbd5f2f69f/src/amcrest/http.py#L152-L162

I can _sort of_ reproduce this on demand by simulating network congestion with `iptables`.  The below rule drops 90% of packets destined for the camera at random.  This causes lots of `ReadTimeout` errors, which makes sense, but it also causes `LoginError` every few minutes.
```
 iptables -A OUTPUT -p tcp -d 192.168.20.10 -m statistic --mode random --probability 0.9 -j DROP
```

**Comment by junalmeida** [comment]
Here is my log when the occasional error happens. The model is Amcrest Doorbell AD410. The password does not contain any special chars, as suggested this would be the cause. 


``` 
2023-02-02 10:30:07.080 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Async HTTP query 270: http://doorbell.****:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo
2023-02-02 10:30:07.112 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Running query 270 attempt 1
2023-02-02 10:30:07.249 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Query 270 worked. Exit code: <200>
2023-02-02 10:30:16.811 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Async HTTP query 271: http://doorbell.****:80/cgi-bin/configManager.cgi?action=getConfig&name=LeLensMask
2023-02-02 10:30:16.843 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Running query 271 attempt 1
2023-02-02 10:30:16.859 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Async HTTP query 272: http://doorbell.****:80/cgi-bin/configManager.cgi?action=getConfig&name=Encode
2023-02-02 10:30:16.887 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Running query 272 attempt 1
2023-02-02 10:30:16.890 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Async HTTP query 273: http://doorbell.****:80/cgi-bin/configManager.cgi?action=getConfig&name=RecordMode
2023-02-02 10:30:16.916 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Running query 273 attempt 1
2023-02-02 10:30:16.918 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Async HTTP query 274: http://doorbell.****:80/cgi-bin/configManager.cgi?action=getConfig&name=MotionDetect
2023-02-02 10:30:16.946 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Running query 274 attempt 1
2023-02-02 10:30:16.948 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Async HTTP query 275: http://doorbell.****:80/cgi-bin/configManager.cgi?action=getConfig&name=Encode
2023-02-02 10:30:16.973 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Running query 275 attempt 1
2023-02-02 10:30:16.975 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Async HTTP query 276: http://doorbell.****:80/cgi-bin/configManager.cgi?action=getConfig&name=MotionDetect
2023-02-02 10:30:17.000 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Running query 276 attempt 1
2023-02-02 10:30:17.003 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Async HTTP query 277: http://doorbell.****:80/cgi-bin/configManager.cgi?action=getConfig&name=VideoInOptions
2023-02-02 10:30:17.029 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Running query 277 attempt 1
2023-02-02 10:30:17.087 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Async HTTP query 278: http://doorbell.****:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo
2023-02-02 10:30:17.111 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Running query 278 attempt 1
2023-02-02 10:30:17.254 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Query 271: Unauthorized (401)
2023-02-02 10:30:17.256 ERROR (MainThread) [homeassistant.components.amcrest] Bell camera offline: Login error: 
2023-02-02 10:30:17.271 ERROR (MainThread) [homeassistant.helpers.entity] Update for switch.bell_privacy_mode fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 548, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 746, in async_device_update
    raise exc
  File "/usr/src/homeassistant/homeassistant/components/amcrest/switch.py", line 89, in async_update
    io_res = (await self._api.async_privacy_config()).splitlines()[0].split("=")[1]
  File "/usr/local/lib/python3.10/site-packages/amcrest/privacy_mode.py", line 42, in async_privacy_config
    return await self._async_get_config("LeLensMask")
  File "/usr/local/lib/python3.10/site-packages/amcrest/http.py", line 464, in _async_get_config
    ret = await self.async_command(
  File "/usr/src/homeassistant/homeassistant/components/amcrest/__init__.py", line 205, in async_command
    ret = await super().async_command(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/amcrest/http.py", line 230, in async_command
    return await self._async_command(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/amcrest/http.py", line 351, in _async_command
    raise LoginError()
amcrest.exceptions.LoginError
2023-02-02 10:30:17.319 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Query 274 worked. Exit code: <200>
2023-02-02 10:30:17.320 ERROR (MainThread) [homeassistant.components.amcrest] Bell camera back online
2023-02-02 10:30:17.340 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Query 278 worked. Exit code: <200>
2023-02-02 10:30:17.349 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Query 272 worked. Exit code: <200>
2023-02-02 10:30:17.849 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Query 273 worked. Exit code: <200>
2023-02-02 10:30:18.386 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Query 276 worked. Exit code: <200>
2023-02-02 10:30:18.909 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Query 275 worked. Exit code: <200>
2023-02-02 10:30:18.918 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Query 277 worked. Exit code: <200>
2023-02-02 10:30:27.087 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Trying async Basic Authentication
2023-02-02 10:30:27.087 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Async HTTP query 279: http://doorbell.****:80/cgi-bin/magicBox.cgi?action=getMachineName
2023-02-02 10:30:27.117 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Running query 279 attempt 1
2023-02-02 10:30:27.254 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Query 279: Unauthorized (401)
2023-02-02 10:30:27.255 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Trying async Digest Authentication
2023-02-02 10:30:27.255 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Async HTTP query 280: http://doorbell.****:80/cgi-bin/magicBox.cgi?action=getMachineName
2023-02-02 10:30:27.285 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Running query 280 attempt 1
2023-02-02 10:30:27.384 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Query 280 worked. Exit code: <200>
2023-02-02 10:30:27.385 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Retrieving serial number
2023-02-02 10:30:27.385 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Async HTTP query 281: http://doorbell.****:80/cgi-bin/magicBox.cgi?action=getSerialNo
2023-02-02 10:30:27.411 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Running query 281 attempt 1
2023-02-02 10:30:27.966 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Query 281 worked. Exit code: <200>
2023-02-02 10:30:27.967 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Async HTTP query 282: http://doorbell.****:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo
2023-02-02 10:30:27.996 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Running query 282 attempt 1
2023-02-02 10:30:28.521 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Query 282 worked. Exit code: <200>
``` 

The query that fails seems to be `/cgi-bin/configManager.cgi?action=getConfig&name=LeLensMask`, but that very same call succeeds right after:

``` 
2023-02-02 10:30:46.812 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Async HTTP query 291: http://doorbell.****:80/cgi-bin/configManager.cgi?action=getConfig&name=LeLensMask
2023-02-02 10:30:46.840 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Running query 291 attempt 1
``` 
```
2023-02-02 10:30:47.855 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Query 291 worked. Exit code: <200>
``` 


Ocasionally I also see this:

``` 
2023-02-02 10:38:09.094 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Query 528 failed due to error: ReadTimeout('')
2023-02-02 10:38:09.094 WARNING (MainThread) [amcrest.http] <Bell:Z17****> Trying again due to error: ReadTimeout('')
2023-02-02 10:38:09.097 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Running query 528 attempt 2
2023-02-02 10:38:09.100 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Query 527 failed due to error: ReadTimeout('')
2023-02-02 10:38:09.101 WARNING (MainThread) [amcrest.http] <Bell:Z17****> Trying again due to error: ReadTimeout('')
2023-02-02 10:38:09.102 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Running query 527 attempt 2
2023-02-02 10:38:09.105 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Query 530 failed due to error: ReadTimeout('')
2023-02-02 10:38:09.106 WARNING (MainThread) [amcrest.http] <Bell:Z17****> Trying again due to error: ReadTimeout('')
2023-02-02 10:38:09.108 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Running query 530 attempt 2
2023-02-02 10:38:09.111 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Query 526 failed due to error: ReadTimeout('')
2023-02-02 10:38:09.112 WARNING (MainThread) [amcrest.http] <Bell:Z17****> Trying again due to error: ReadTimeout('')
2023-02-02 10:38:09.117 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Running query 526 attempt 2
2023-02-02 10:38:09.120 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Query 523 failed due to error: ReadTimeout('')
2023-02-02 10:38:09.121 WARNING (MainThread) [amcrest.http] <Bell:Z17****> Trying again due to error: ReadTimeout('')
2023-02-02 10:38:09.123 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Running query 523 attempt 2
2023-02-02 10:38:09.126 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Query 525 failed due to error: ReadTimeout('')
2023-02-02 10:38:09.127 WARNING (MainThread) [amcrest.http] <Bell:Z17****> Trying again due to error: ReadTimeout('')
2023-02-02 10:38:09.130 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Running query 525 attempt 2
2023-02-02 10:38:09.134 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Query 529 failed due to error: ReadTimeout('')
2023-02-02 10:38:09.134 WARNING (MainThread) [amcrest.http] <Bell:Z17****> Trying again due to error: ReadTimeout('')
2023-02-02 10:38:09.140 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Running query 529 attempt 2
2023-02-02 10:38:09.670 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Query 530 worked. Exit code: <200>
2023-02-02 10:38:09.704 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Query 528 worked. Exit code: <200>
2023-02-02 10:38:09.707 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Query 523 worked. Exit code: <200>
2023-02-02 10:38:09.708 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Query 526 worked. Exit code: <200>
2023-02-02 10:38:10.297 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Query 527 worked. Exit code: <200>
2023-02-02 10:38:10.355 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Query 529 worked. Exit code: <200>
2023-02-02 10:38:10.704 DEBUG (MainThread) [amcrest.http] <Bell:Z17****> Query 525 worked. Exit code: <200>
``` 

(device serial and domain redacted)

**Comment by llamafilm** [comment]
This seems like maybe an issue with `httpx`, maybe the `_async_token` is being lost somehow.  I might try adding a debug logger for the `client` object right before each call.

**Comment by llamafilm** [comment]
@junalmeida I think the ReadTimeouts are irrelevant, it just suggests your network is congested or the camera is slow to respond.  This LoginError seems to happen randomly with any call.  Besides `LeLensMask`, I've also seen it on `getCurrentTime` (and probably others, but I haven't been tracking it closely).

I added `_LOGGER.debug('auth: %s', vars(self._token))` to [line 344](https://github.com/tchellomello/python-amcrest/blob/b9883a246d92580d49d2c6c6435af1dbd5f2f69f/src/amcrest/http.py#L344) just before each `get` call and I see some interesting things, but I don't know what to make of this.

It fires 7 async requires at the same time (within 300ms), of which 6 use the same nonce.  The one that fails is the only one with a different nonce.

The `_nonce_count` is never 1, it always starts at 2.

**Comment by dannybloe** [comment]
I am seeing the same problems. I also noticed that when Home Assistant (using the library) tries to connect with my doorbell and the log show these timeout errors, I can manually connect with the doorbell's api using PostMan without any problem. All the times this happens. I think that about 50% of the time HA fails to connect with the doorbell when it reboots.
I'm very sure there's no congestion on my local network whatsoever.

**Comment by drjjr2** [comment]
I see this same issue with an AD410. Intermittent login errors.
```
2023-04-14 07:29:45.421 DEBUG (MainThread) [homeassistant.components.amcrest.camera] Take snapshot from Front Door Bell
2023-04-14 07:29:45.422 DEBUG (MainThread) [homeassistant.components.amcrest.camera] Take snapshot from Front Door Bell Sub
2023-04-14 07:29:45.431 DEBUG (MainThread) [amcrest.http] <Z17C1C0CFE5F4:Z17C1C0CFE5F4> Async HTTP query 33488: http://192.168.0.39:80/cgi-bin/snapshot.cgi
2023-04-14 07:29:45.465 DEBUG (MainThread) [amcrest.http] <Z17C1C0CFE5F4:Z17C1C0CFE5F4> Running query 33488 attempt 1
2023-04-14 07:29:45.467 DEBUG (MainThread) [amcrest.http] <Z17C1C0CFE5F4:Z17C1C0CFE5F4> Async HTTP query 29563: http://192.168.0.39:80/cgi-bin/snapshot.cgi
2023-04-14 07:29:45.500 DEBUG (MainThread) [amcrest.http] <Z17C1C0CFE5F4:Z17C1C0CFE5F4> Running query 29563 attempt 1
2023-04-14 07:29:45.724 DEBUG (MainThread) [amcrest.http] <Z17C1C0CFE5F4:Z17C1C0CFE5F4> Query 29558 worked. Exit code: <200>
2023-04-14 07:29:45.775 DEBUG (MainThread) [amcrest.http] <Z17C1C0CFE5F4:Z17C1C0CFE5F4> Query 33487: Unauthorized (401)
2023-04-14 07:29:45.778 ERROR (MainThread) [homeassistant.components.amcrest] Front Door Bell camera offline: Login error: 
2023-04-14 07:29:45.781 DEBUG (MainThread) [homeassistant.components.amcrest.binary_sensor] Updating Front Door Bell Online binary sensor
2023-04-14 07:29:45.803 ERROR (MainThread) [homeassistant.components.amcrest.camera] Could not get Front Door Bell camera attributes due to error: LoginError
2023-04-14 07:29:45.829 DEBUG (MainThread) [amcrest.http] <Z17C1C0CFE5F4:Z17C1C0CFE5F4> Query 29559 worked. Exit code: <200>
2023-04-14 07:29:46.324 DEBUG (MainThread) [amcrest.http] <Z17C1C0CFE5F4:Z17C1C0CFE5F4> Query 29560 worked. Exit code: <200>
2023-04-14 07:29:46.342 DEBUG (MainThread) [amcrest.http] <Z17C1C0CFE5F4:Z17C1C0CFE5F4> Query 29557 worked. Exit code: <200>
2023-04-14 07:29:46.846 DEBUG (MainThread) [amcrest.http] <Z17C1C0CFE5F4:Z17C1C0CFE5F4> Query 29562 worked. Exit code: <200>
2023-04-14 07:29:46.858 DEBUG (MainThread) [amcrest.http] <Z17C1C0CFE5F4:Z17C1C0CFE5F4> Query 33486 worked. Exit code: <200>
2023-04-14 07:29:46.858 ERROR (MainThread) [homeassistant.components.amcrest] Front Door Bell camera back online
2023-04-14 07:29:46.862 DEBUG (MainThread) [homeassistant.components.amcrest.binary_sensor] Updating Front Door Bell Online binary sensor
```
